name: CI - Integración Continua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Obtener código fuente
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Instalar dependencias
      run: |
        npm install

    - name: Ejecutar pruebas
      run: npm run lint --if-present

    - name: Ejecutar aplicación
      run: npm run build